name: task1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_osm_plugin: ^1.3.6
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  lottie: ^3.3.1
  meta: ^1.15.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.json
